# Generated by Django 2.2 on 2021-03-06 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210306_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating_count',
            field=models.PositiveIntegerField(default=55),
        ),
    ]
